[versions]
agp = "8.13.2"
androidxNavigation = "2.6.0"
kotlin = "1.9.0"
purchases = "10.20.0"
lifecycle = "2.6.1"
androidxCore = "1.10.1"
recyclerView = "1.3.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
material = "com.google.android.material:material:1.9.0"
revenuecat = { module = "com.revenuecat.purchases:purchases", version.ref = "purchases" }
revenuecat-ui = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "purchases" }
