const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8080/app/v4.html');
 await page.getByRole('button',{name:'Sign in / Create account',exact:true}).click();
 const email='companion-ci-'+Date.now()+'@example.test';
 await page.locator('#regName').fill('CI participant');
 await page.locator('#regEmail').fill(email);
 await page.locator('#regPassword').fill('SafeCircleTest123!');
 await page.locator('#regConfirm').fill('SafeCircleTest123!');
 await page.locator('#regTerms').check();
 await page.locator('#registerBtn').click();
 await page.getByRole('button',{name:'Account ✓',exact:true}).waitFor();
 await page.getByRole('button',{name:'Start protection',exact:true}).click();
 await page.locator('#dest').fill('Test destination');
 await page.locator('#startNow').click();
 await page.locator('#checkBtn').waitFor();
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('safecircle_web_v4')));
 let state=await saved();assert.equal(state.active.privacyMode,'STATUS_ONLY');
 const initial=state.active;
 // Failure must not falsely resolve or move the ETA.
 await page.route('**/v1/sessions/'+initial.id+'/resolve',r=>r.fulfill({status:503,contentType:'application/json',body:'{"detail":"Test provider unavailable"}'}));
 await page.locator('#safeBtn').click();
 await page.locator('#toast').filter({hasText:'no server change confirmed'}).waitFor();
 assert.equal((await saved()).active.resolvedAt,null);
 await page.unroute('**/v1/sessions/'+initial.id+'/resolve');
 await page.locator('#extendBtn').click();
 await page.waitForFunction(t=>JSON.parse(localStorage.getItem('safecircle_web_v4')).active.expectedSafeAt>t, initial.expectedSafeAt);
 state=await saved();assert.equal(state.active.expectedSafeAt,initial.expectedSafeAt+900000);
 // Server check-in response, not a local guess, is the canonical state.
 const canonical={id:initial.id,owner_id:state.auth.user_id,mode:'WALK_HOME',started_at:initial.startedAt,expected_end_at:Date.now()+300000,last_check_in_at:Date.now(),privacy_mode:'STATUS_ONLY',state:'NORMAL'};
 await page.route('**/v1/sessions/'+initial.id+'/check-in',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({session:canonical})}));
 await page.locator('#checkBtn').click();
 await page.waitForFunction(t=>JSON.parse(localStorage.getItem('safecircle_web_v4')).active.expectedSafeAt===t,canonical.expected_end_at);
 await page.unroute('**/v1/sessions/'+initial.id+'/check-in');
 await page.getByRole('button',{name:/Guardian Operations/}).click();
 await page.locator('#backupGuardian').click();
 await page.getByRole('heading',{name:'Backup Guardian link',exact:true}).waitFor();
 await page.locator('#primaryGuardian').click();
 await page.getByRole('heading',{name:'Primary Guardian link',exact:true}).waitFor();
 await page.locator('#closePanel').click();
 await page.locator('#safeBtn').click();
 await page.getByRole('button',{name:'View receipt',exact:true}).waitFor();
 assert.ok((await saved()).active.resolvedAt);
 await page.reload();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('safecircle_web_v4')).history.length===1);
 assert.equal((await saved()).history[0].id,initial.id);
 await page.getByRole('button',{name:'Account ✓',exact:true}).click();
 await page.locator('#logoutBtn').click();
 await page.getByRole('button',{name:'Sign in / Create account',exact:true}).waitFor();
 state=await saved();assert.equal(state.auth,null);assert.equal(state.active,null);assert.deepEqual(state.guardians,[]);assert.deepEqual(state.history,[]);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Companion registration, privacy, failed resolution, ETA, canonical check-in, Primary/Backup labels, durable history and logout isolation passed.');
})().catch(e=>{console.error(e);process.exit(1)});
