const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:720,height:720}});
 const failures=[];page.on('pageerror',e=>failures.push(e.message));
 await page.goto('http://127.0.0.1:8080/site/demo.html?stage=5');
 if(!(await page.locator('#status').innerText()).includes('overdue'))throw Error('Stage 5 missing');
 await page.screenshot({path:'web/site/assets/guardian-demo.png'});
 for(const stage of ['10','15','safe'])await page.locator(`[data-stage="${stage}"]`).click();
 if(await page.locator('#status').innerText()!=='Marked safe')throw Error('Resolution demo failed');
 await page.goto('http://127.0.0.1:8080/');
 if(!page.url().endsWith('/site/'))throw Error('Landing redirect missing');
 await page.screenshot({path:'web/site/assets/landing-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'web/site/assets/landing-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 await page.goto('http://127.0.0.1:8080/guardian/');
 if(!(await page.locator('#explain').innerText()).includes('No Guardian token'))throw Error('Guardian fallback leaked');
 const email='guardian-ci-'+Date.now()+'@example.test', password='SafeCircleTest123!';
 const authResponse=await page.request.post('http://127.0.0.1:8080/v1/auth/register',{data:{email,password}});
 if(!authResponse.ok())throw Error('Test account failed');
 const auth=await authResponse.json(), headers={Authorization:'Bearer '+auth.access_token};
 const now=Date.now(), id='web-ci-'+now;
 const session={id,owner_id:auth.user_id,mode:'WALK_HOME',started_at:now-3600000,expected_end_at:now-16*60000,last_check_in_at:now-3600000,privacy_mode:'STATUS_ONLY',latitude:32.12345,longitude:-97.12345,capsule:{instruction:'Call first',primaryContact:'+15555550111',expiresAt:now+60000}};
 const created=await page.request.post('http://127.0.0.1:8080/v1/sessions',{headers,data:session});
 if(!created.ok())throw Error('Test session failed');
 const inviteResponse=await page.request.post('http://127.0.0.1:8080/v1/guardian-invites',{headers,data:{session_id:id,owner_id:auth.user_id,role:'primary',ttl_minutes:5}});
 const invite=await inviteResponse.json();
 await page.goto(invite.guardian_url);
 await page.getByRole('button',{name:"I'm watching"}).click();
 await page.waitForFunction(()=>document.getElementById('guardianActionStatus').textContent.includes('acknowledged'));
 const view=await (await page.request.get('http://127.0.0.1:8080/v1/public/guardian/'+invite.guardian_token)).json();
 if(view.location!==null||view.safety_capsule.primaryContact!==undefined)throw Error('Guardian privacy failure');
 if(!(await page.locator('#capsuleDetails').innerText()).includes('Call first'))throw Error('Guardian instruction missing');
 await page.request.post('http://127.0.0.1:8080/v1/sessions/'+id+'/resolve',{headers,data:{}});
 await page.waitForFunction(()=>document.getElementById('status').textContent.includes('Resolved'));
 if(await page.getByRole('button',{name:"I'm watching"}).isEnabled())throw Error('Resolved Guardian can act');
 const removed=await page.request.delete('http://127.0.0.1:8080/v1/account',{headers,data:{email,password}});
 if(!removed.ok())throw Error('Account deletion failed');
 await page.goto('http://127.0.0.1:8080/site/privacy.html');
 if(!(await page.title()).includes('Privacy'))throw Error('Privacy policy missing');
 if(failures.length)throw Error(failures.join('\n'));
 await page.setViewportSize({width:1024,height:1024});
 await page.goto('http://127.0.0.1:8080/site/assets/app-icon.svg');
 await page.screenshot({path:'web/site/assets/app-icon-1024.png'});
 await browser.close();console.log('Desktop/mobile landing, simulated stages, signed Guardian acknowledgement/privacy/resolution, account deletion and no-token checks passed.');
})();
